version: "3.3"
services:
    api:
        build:
            context: ./api
        ports:
            - 8000:8000
        depends_on:
            - db
        # networks:
        #     - backend
    db:
        image: postgres:14.1
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=tsa-canvas-db
    app:
        build:
            context: ./app
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/localhost.crt:/etc/nginx/localhost.crt
            - ./nginx/localhost.key:/etc/nginx/localhost.key
        ports:
            - 80:80
            - 443:443
        depends_on:
            - api
volumes:
    db-data:
# networks:
#     frontend:
#     backend:
