version: "3.3"
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/localhost.crt:/etc/nginx/localhost.crt
            - ./nginx/localhost.key:/etc/nginx/localhost.key
        env_file:
            - .env
        ports:
            - 80:80
            - 443:443
            - 9000:9000
        depends_on:
            - api
            - app
    api:
        build:
            context: ./api
            dockerfile: ./Dockerfile.dev
        env_file:
            - .env
        ports:
            - 8000:8000
        depends_on:
            - db
        volumes:
            - ./api/node_modules/:/api/node_modules
            - ./api/src/:/api/src
            - ./api/prisma/:/api/prisma
        environment:
            - DATABASE_URL=postgresql://postgres:password@tsa-canvas-db-1:5432/tsa-canvas-db
            - PORT=8000
            - JWT_SECRET=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTQ2Nzc3MzQ5Nn0.v0Gfc9fKDQfkDningjmObkD5-EcbfWy5vuvuOimTV032iCoOaaQtCsZxQC78JbLbeQNLUA3UaQnuLgvwwqLmIg
    db:
        image: postgres:14.1
        env_file:
            - .env
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=tsa-canvas-db
    minio:
        image: minio/minio:latest
        env_file:
            - .env
        command: server /data --console-address ":9001"
        volumes:
            - ./data/minio:/data
        ports:
            # - 9000:9000
            - 9001:9001
    app:
        build:
            context: ./app
            dockerfile: ./Dockerfile.dev
        env_file:
            - .env
        environment:
            - PORT=3000
        ports:
            - 3000:3000
        volumes:
            - ./app/node_modules/:/app/node_modules
            - ./app/src/:/app/src
            - ./app/static/:/app/static
            - ./app/zeus/:/app/zeus
    # Create buckets for minio.
    createbuckets:
        image: minio/mc
        depends_on:
            - minio
        env_file: .env
        entrypoint: >
            /bin/sh -c "
            while ! curl -s --output /dev/null --connect-timeout 1 http://tsa-canvas-minio-1:9000; do echo 'Waiting minio...' && sleep 0.1; done;
            /usr/bin/mc alias set minio http://tsa-canvas-minio-1:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
            /usr/bin/mc mb minio/upload;
            /usr/bin/mc policy set public minio/upload;
            exit 0;
            "
volumes:
    db-data:
